version: '3.8'

services:
  nagios:
    build: .
    container_name: nagios-core
    ports:
      - "9090:80"
    volumes:
      - nagios-config:/usr/local/nagios/etc
      - nagios-plugins:/usr/local/nagios/libexec
    environment:
      - NAGIOSADMIN_USER=nagiosadmin
      - NAGIOSADMIN_PASS=nagiosadmin
    entrypoint: ["/entrypoint.sh"]

volumes:
  nagios-config:
  nagios-plugins:

